# Simulation of co-circulation of rift fever and differences between
# simultaneous and offset seroprevalence sampling in humans and livestock.

# Data come from Metras et al (2016, https://dx.doi.org/10.1371/journal.pntd.0004783)
# and are re-sampled to create livestock time series.  Human series is simulated.

P <- rprojroot::find_rstudio_root_file
library(dplyr)
library(readr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(noamtools)
library(zoo)

# Load in the Metras et al. data set
# This CSV was generated by running `metra_seroprevalence_plot` the
# tool at http://arohatgi.info/WebPlotDigitizer/
metra <- read_csv(P("data", "metra_data.csv"), col_names=FALSE) %>%
  rename(time=X1, livestock_sero=X2) %>%
  mutate(date=floor_date(date_decimal(time), "month"),
         livestock_sero = round(livestock_sero, 2))

# Resample monthly and simulate a human time series
date_seq = data_frame(date=seq.POSIXt(min(metra$date), max(metra$date), "month"))
all_simulation = full_join(metra, date_seq) %>%
  arrange(date) %>%
  mutate(time = decimal_date(date), original = ifelse(is.na(original), FALSE, TRUE)) %>%
  mutate(livestock_sero = na.locf(livestock_sero)) %>%
  mutate(circulation = pmax(0, livestock_sero - lag(livestock_sero))) %>%
  mutate(farmer_sero = 0.1 + c(0, cumsum(circulation[-1] + rnorm(n()-1, 0, 0.025))/5) - seq(0, 0.4, length.out =n()))


#Subsample the monthly time series every four months
sample_together = all_simulation %>%
  filter(1:n() %% 4 == 0) %>%
  mutate(livestock_chg = livestock_sero - lag(livestock_sero),
         farmer_chg = farmer_sero - lag(farmer_sero))

#The same, but offset human samples by 2 months
sample_offset = all_simulation %>%
  mutate(farmer_sero = lead(farmer_sero, 2)) %>%
  filter(1:n() %% 4 == 0) %>%
  mutate(livestock_chg = livestock_sero - lag(livestock_sero),
         farmer_chg = farmer_sero - lag(farmer_sero))

#Plot time series
simulation_plot =
  sample_together %>%
  gather("pop", "sero", livestock_sero, farmer_sero) %>%
  ggplot(aes(x=time - min(time), y=sero, col=pop)) +
  geom_line(lwd=1) +
  geom_point(size=3) +
  scale_x_continuous(breaks=2*0:5, name="Years") +
  scale_y_continuous(labels=scales::percent, name="Seroprevalence") +
  scale_color_discrete(labels = c("Humans", "Livestock")) +
  theme_nr
ggsave("simulation.png", simulation_plot, width = 8, height=4.5, units="in", dpi=150)

# Plot human/animal correlation in changes in seroprevalence for both sampling
# cases
stat_plot_1 =
ggplot(sample_together, aes(x=livestock_chg, y=farmer_chg)) +
  geom_point(size=3) +
  geom_smooth(method="lm") +
  scale_y_continuous(name = "Change in Farmer Seroprevalence", limits=c(-0.1, 0.1)) +
  theme_nr +
  xlab("Change in Livestock Seroprevalence")
ggsave("stat_1.png", stat_plot_1, width = 4, height=4, units="in", dpi=150)


stat_plot_2 =
  ggplot(sample_offset, aes(x=livestock_chg, y=farmer_chg)) +
  geom_point(size = 3) +
  geom_smooth(method="lm") +
  theme_nr +
  scale_y_continuous(name = "Change in Farmer Seroprevalence", limits=c(-0.1, 0.1)) +
  xlab("Change in Livestock Seroprevalence")
ggsave("stat_2.png", stat_plot_2, width = 4, height=4, units="in", dpi=150)



model_together =  lm(farmer_chg~livestock_chg, data=sample_together)

model_offset =  lm(farmer_chg~livestock_chg, data=sample_offset)



  mutate(farmer_chg = 12*(farmer_sero - lag(farmer_sero))/(time - lag(time)))

metra4 = metra2 %>%
  mutate(farmer_samp = sample(original, n(), replace=FALSE)) %>%
  filter(farmer_samp) %>%
  mutate(farmer_chg = 12*(farmer_sero - lag(farmer_sero))/(time - lag(time))) %>%
  filter(original)








model1 <-
model2 <- lm(farmer_chg~livestock_sero, data=metra4)
summary(model1)
summary(model2)


# Simulate a process: Farmer seroprevalence rises with livestock seroprevalence

metra %<>%
  mutate(farmer_sero =
